//var LOAD_ENTITIES_URL = 'http://localhost/api/entity';
module.exports = {
	LOAD_ENTITIES: "LOAD_ENTITIES",
	LOAD_ENTITIES_SUCCESS: "LOAD_ENTITIES_SUCCESS",
 	LOAD_ENTITIES_FAIL: "LOAD_ENTITIES_FAIL",
  	RECEIVE_ENTITIES: "RECEIVE_ENTITIES",   
};